site_name: SOLA
site_author: The SOLA team @ Fraunhofer IML
site_description: Documentation about SOLA
site_dir: html
site_url: https://iml130.github.io/sola/
use_directory_urls: false

repo_name: iml130/sola
repo_url: https://github.com/iml130/sola
edit_uri: ""

nav:
  - Introduction:
    - Introduction: index.md

    # - Project Structure: highlevel.md
    # - Installation: installation.md
    # - Contributing: contributing.md
  - SOLA:
    - Introduction: sola/introduction.md
    - Getting Started: getting_started.md
    - Glossary: sola/glossary.md
  - MINHTON: 
    - Introduction: management_overlay/introduction.md
    - Getting Started: management_overlay/getting_started.md
    - Programmers Manual:
      - Concept: management_overlay/programmers/concept.md
      - Messages: management_overlay/programmers/messages.md
      - Logging: management_overlay/programmers/logging.md
      - Algorithms:
        - Introduction: management_overlay/algorithms/index.md
        - Join: management_overlay/algorithms/join.md
        - Join Accept: management_overlay/algorithms/join_accept.md
        - Leave: management_overlay/algorithms/leave.md
        - Concurrent Leave: management_overlay/algorithms/leave_concurrent.md
        - Bootstrap: management_overlay/algorithms/bootstrap.md
        - TreeMapper: management_overlay/algorithms/treemapper.md
      - FSM: management_overlay/programmers/fsm.md
    - Glossary: management_overlay/glossary.md
  - NATTER: 
    - Introduction: natter_lib/introduction.md
    - Getting Started: natter_lib/getting_started.md
    - Programmers Manual:
      - Architecture: natter_lib/programmers/architecture.md
      - Logging: natter_lib/programmers/logging.md
      - Algorithms:
        - MINHCAST: natter_lib/programmers/minhcast.md
    - Known Limitations: natter_lib/known-limitations.md
    - Glossary: natter_lib/glossary.md
  - Applications: 
    - Introduction: applications/getting_started.md
    - OptiMaFlow: 
      - Getting Started: applications/optimaflow/getting_started.md
      - Participants:
        - Material Flow: applications/optimaflow/material_flow.md
        - AMR/AGV: applications/optimaflow/amr_agv.md
        - Optimizer: applications/optimaflow/optimization.md
      - Algorithms:
        - ContractNet: applications/optimaflow/contract_net.md
        - RoundRobin: applications/optimaflow/round_robin.md
        
      - Logging: applications/optimaflow/logging.md 
    - Glossary: applications/glossary.md
      
  - ns-3 Integration: 
    - Getting started: daisi/index.md
    - Logging: daisi/logging.md
    - SOLA:
      - Environments: sola/environments.md
      - Messages: ns-3/messages.md
    - Scenario Files: ns-3/scenario_files.md
    - Events: ns-3/events.md
    - Network: ns-3/network.md
    - MINHTON:
      - Scenariofile: daisi/minhton-ns3/management-overlay.md
      - ESearch: daisi/minhton-ns3/esearch.md    
    - NATTER:
      - Scenariofile: daisi/natter-ns3/event-distribution.md
    # - Use-Cases:
    #   - Getting started: ns-3/index.md
    #   - Intralogistics: daisi/natter-ns3/event-distribution.md
    #   - (Path Planning): daisi/applications/path-planning/index.md
    # - Glossary: daisi/glossary.md
  - Doxygen: doxygen/index.html
  - Glossary: glossary.md

theme:
  name: material

  palette:
    - scheme: sola

  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top # back to top button visible
    - navigation.tracking
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font: false # Use system fonts

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

extra_css:
    - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; The SOLA authors
