site_name: SOLA
site_author: The SOLA team @ Fraunhofer IML
site_description: Documentation about SOLA
site_dir: html
site_url: https://iml130.github.io/sola/
use_directory_urls: false

repo_name: iml130/sola
repo_url: https://github.com/iml130/sola
edit_uri: ""

nav:
  - Home:
    - Index: index.md
    - Introduction: index.md
    - Getting Started: getting_started.md
    - SOLA:
      - Using SOLA: sola/usage.md
      - Component Implementations: sola/component_implementations.md
      - "Example: Decentralized Communication": sola/decentralized_communication.md
      - Logging: sola/logging.md
      - Glossary: sola/glossary.md
  - MINHTON:
    - Introduction: management_overlay/introduction.md
    - Using MINHTON: management_overlay/using.md
    - Programmers Manual:
      - Concept: management_overlay/programmers/concept.md
      - Messages: management_overlay/programmers/messages.md
      - Algorithms:
        - Introduction: management_overlay/algorithms/index.md
        - Join: management_overlay/algorithms/join.md
        - Join Accept: management_overlay/algorithms/join_accept.md
        - Leave: management_overlay/algorithms/leave.md
        - Concurrent Leave: management_overlay/algorithms/leave_concurrent.md
        - Bootstrap: management_overlay/algorithms/bootstrap.md
        - TreeMapper: management_overlay/algorithms/treemapper.md
      - FSM: management_overlay/programmers/fsm.md
    - Glossary: management_overlay/glossary.md
  - NATTER:
    - Index: natter/index.md
    - Introduction: natter/index.md
    - Using natter: natter/using.md
    - Programmers Manual:
      - Architecture: natter/programmers/architecture.md
      - Logging: natter/programmers/logging.md
      - Algorithms:
        - MINHCAST: natter/programmers/minhcast.md
    - Known Limitations: natter/known-limitations.md
    - Glossary: natter/glossary.md
  - OptiMaFlow:
    - Introduction: optimaflow/introduction.md
    - Participants:
      - Overview: optimaflow/participants/overview.md
      - Material Flow: optimaflow/participants/material_flow.md
      - AMR: optimaflow/participants/amr.md
    - Task Assignment:
      - Decentralized: optimaflow/task_assignment/decentralized.md
      - Centralized: optimaflow/task_assignment/round_robin.md
    - Logging: optimaflow/logging.md
    - Glossary: optimaflow/glossary.md

  - ns-3 Integration:
    - Introduction: daisi/introduction.md
    - Getting started: daisi/getting_started.md
    - Logging: daisi/logging.md
    - Network: daisi/network.md
    - SOLA:
      - Scenariofile: daisi/sola-ns3/scenario_files.md
      - Environments: daisi/sola-ns3/environments.md
      - Logging: daisi/sola-ns3/logging.md
    - MINHTON:
      - Scenariofile: daisi/minhton-ns3/scenariofile.md
      - Logging: daisi/minhton-ns3/logging.md
      - ESearch: daisi/minhton-ns3/esearch.md
    - NATTER:
      - Scenariofile: daisi/natter-ns3/scenariofile.md
      - Logging: daisi/natter-ns3/logging.md
    - OptiMaFlow:
      - Scenariofile: daisi/optimaflow-ns3/scenariofile.md
      - Logging: daisi/optimaflow-ns3/logging.md

  - Doxygen: doxygen/index.html
  - Glossary: glossary.md

theme:
  name: material

  palette:
    - scheme: sola

  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top # back to top button visible
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font: false # Use system fonts

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Copyright &copy; The SOLA authors
