title: Test
version: 0.1
stop_time: 5000
random_seed: 1
default_delay: 500

# outdated/unused fields
# only present until Manager switches to new scenariofile parser as well
randomSeed: 1
stoptime: 5000000

fanout: 2
number_nodes: 20
mode: minhcast # minhcast

scenario_sequence:
    - type: join
      mode: minhton
    - type: publish
      number: 5
      delay: 0
      mode: random # random, sequential
      message_size: 100 # in bytes
