title: Test
version: 0.1
stop_time: 5000s
random_seed: 1
default_delay: 0.5s

fanout: 2
number_nodes: 20
mode: minhcast # minhcast

scenario_sequence:
    - type: join
      mode: minhton
    - type: publish
      number: 5
      delay: 0s
      mode: random # random, sequential
      message_size: 100 # in bytes
