title: SOLA default scenario
version: 0.1
stop_time: 4294967296
random_seed: 1
default_delay: 500

# outdated/unused fields
# only present until Manager switches to new scenariofile parser as well
stoptime: 4294967296
randomSeed: 1

fanout: 2
number_nodes: 3

scenario_sequence:
  - type: start_sola
    delay: 1000
  - type: delay
    delay: 0
  - type: subscribe_topic
    topic: "helloworld"
    delay: 1000
  - type: delay
    delay: 0
  - type: publish
    topic: "helloworld"
    message_size: 100 # bytes
    node_id: "1"
  - type: publish
    topic: "helloworld"
    message_size: 1000 # bytes
    node_id: 2
