title: SOLA default scenario
version: 0.1
stop_time: 4294967296ms
random_seed: 1
default_delay: 0.5s

fanout: 2
number_nodes: 3

scenario_sequence:
  - type: start_sola
    delay: 1s
  - type: delay
    delay: 0s
  - type: subscribe_topic
    topic: "helloworld"
    delay: 1s
  - type: delay
    delay: 0s
  - type: publish
    topic: "helloworld"
    message_size: 100 # bytes
    node_id: "1"
  - type: publish
    topic: "helloworld"
    message_size: 1000 # bytes
    node_id: 2
